### ISSUE TITLE
Missing changelog for 0.5.1.0 and 0.5.1.1

### ISSUE THREAD

**Issue by andreasabel** [tonyday567/chart-svg#37]
The newly released versions 0.5.1.0 and 0.5.1.1 (thanks!) are missing changelog entries.

**Comment by tonyday567** [comment]
Thanks for the reminder!

2a2076f added this.

Happy to document and discuss the changes in more detail as anyone requires.

**Comment by andreasabel** [comment]
Thanks!

I posted a question here: https://github.com/tonyday567/chart-svg/commit/2a2076f797344326db6dba3430c6b69ea3b5aabb#r126269609

**Comment by tonyday567** [comment]
I'll respond here.

Yes, guilty as charged your honour. Releasing v0.5.0.0 was the initial mistake. I realised this a few days later and pushed out the v0.5.1 versions.

I can think of three options:

- publish v0.5.1.1 as v0.6.0.0 and forge ahead.
- deprecate v0.5.0.0 and dont release a v0.6.  This version made it into the stack dailys for a few days, and I'm otherwise unsure what the implications of deprecation might be.
- do nothing, and perhaps rely on the compiler preference for later versions.

What do you think?

**Comment by andreasabel** [comment]
@tonyday567 wrote:

> Yes, guilty as charged your honour. 

Haha, sorry, as Hackage Trustee I am also playing sometimes the Hackage Police.

> Releasing v0.5.0.0 was the initial mistake. I realised this a few days later and pushed out the v0.5.1 versions.

I think then just deprecate v0.5.0.0 on Hackage.  This is sufficient to mark a release as non PVP compliant (or, more generally, broken in some sense).

**Comment by tonyday567** [comment]
Ok, v0.5.0.0 deprecated on hackage.

Appreciate your input!
